<h1>Login</h1>
<form action="/users/login" method="post">
    <div>
        <label>
            Login:
            <input type="text" name="user[email]" value="<?= htmlspecialchars($userData['email']) ?>">
        </label>
        <?php if (isset($errors['email'])) : ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Login">
</form>