<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><span style="color: green; font-weight: bold;"><?= $message ?></span></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<hr>
<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label>
            Имя:
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? ''); ?>">
        </label>
        <?php if (isset($errors['name'])) : ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>