<h1>Users</h1>
<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><span style="color: green; font-weight: bold;"><?= $message ?></span></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<hr>
<form action="" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>
<hr>
<?php if (count($users) === 0) : ?>
    <div>Users list is empty</div>
<?php else : ?>
    <?php foreach ($users as $id => $user) : ?>
        <div>
            <a href="/users/<?= htmlspecialchars($id) ?>"><?= htmlspecialchars($user['name']) ?></a>
        </div>
    <?php endforeach ?>
<?php endif ?>
<hr>
<div>
    <a href="/users/new">Create a new user</a>
</div>
<form action="/users" method="post">
    <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Clean">
</form>