<h1>New User</h1>
<hr>
<form action="/users" method="post">
    <div>
        <label>
            Nickname:
            <input type="text" name="user[name]" value="<?= htmlspecialchars($userData['name']) ?>" required>
        </label>
        <?php if (isset($errors['name'])) : ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email:
            <input type="email" name="user[email]" value="<?= htmlspecialchars($userData['email']) ?>" required>
        </label>
        <?php if (isset($errors['email'])) : ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Submit">
</form>