<h1>User <?= htmlspecialchars($name) ?></h1>
<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><span style="color: green; font-weight: bold;"><?= $message ?></span></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>
<hr>
<span>id = <?= htmlspecialchars($id) ?></span>
</br>
<span>nickname = <?= htmlspecialchars($name) ?></span>
</br>
<span>email = <?= htmlspecialchars($email) ?></span>
<hr>
<a href="/users/<?= htmlspecialchars($id) ?>/edit">Edit User</a>
<a href="#" style="visibility: <?= $button ?>;">Logout</a>